name: Update pull request branches

on:
  workflow_run:
    workflows:
      - "Ensure Prisma migrations are in sync with the schema"
      - "Docker Build and Push"
      - "Docker Test"
      - "Runs E2E API Tests"
      - "Lint & build"
      - "Mirror main branch to main-mirror-for-wdb"
      - "Preview Docs"
      - "Publish Docs"
      - "Dev Environment Test"
      - "Run setup tests"
      - "TOC Generator"
    types:
      - completed
    conclusion: success

jobs:
  update-pr-branches:
    permissions:
      contents: write
      pull-requests: write
    name: Update pull request branches
    runs-on: ubuntu-22.04
    steps:
      - uses: chinthakagodawita/autoupdate@0707656cd062a3b0cf8fa9b2cda1d1404d74437e
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_CONFLICT_ACTION: 'ignore'
